// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, created_at
`

type CreateMagicLinkParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRow(ctx, createMagicLink, arg.UserID, arg.Token, arg.ExpiresAt)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, csrf_token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, csrf_token, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string             `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CsrfToken string             `db:"csrf_token" json:"csrf_token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredMagicLinks = `-- name: DeleteExpiredMagicLinks :exec
DELETE FROM magic_links WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredMagicLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMagicLinks)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteMagicLink = `-- name: DeleteMagicLink :exec
DELETE FROM magic_links WHERE id = $1
`

func (q *Queries) DeleteMagicLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMagicLink, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getMagicLinkByToken = `-- name: GetMagicLinkByToken :one
SELECT magic_links.id, magic_links.user_id, magic_links.token, magic_links.expires_at, magic_links.created_at, users.email
FROM magic_links
JOIN users ON users.id = magic_links.user_id
WHERE magic_links.token = $1
  AND magic_links.expires_at > NOW()
`

type GetMagicLinkByTokenRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Email     string             `db:"email" json:"email"`
}

func (q *Queries) GetMagicLinkByToken(ctx context.Context, token string) (GetMagicLinkByTokenRow, error) {
	row := q.db.QueryRow(ctx, getMagicLinkByToken, token)
	var i GetMagicLinkByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT sessions.id, sessions.user_id, sessions.csrf_token, sessions.expires_at, sessions.created_at, users.email
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.id = $1
  AND sessions.expires_at > NOW()
`

type GetSessionByIDRow struct {
	ID        string             `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CsrfToken string             `db:"csrf_token" json:"csrf_token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Email     string             `db:"email" json:"email"`
}

func (q *Queries) GetSessionByID(ctx context.Context, id string) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, created_at
`

// +goose StatementBegin
func (q *Queries) UpsertUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}
