// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countResponsesByFormID = `-- name: CountResponsesByFormID :one
SELECT COUNT(*) FROM responses WHERE form_id = $1
`

func (q *Queries) CountResponsesByFormID(ctx context.Context, formID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countResponsesByFormID, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (response_id, question_id, value)
VALUES ($1, $2, $3)
RETURNING id, response_id, question_id, value
`

type CreateAnswerParams struct {
	ResponseID pgtype.UUID `db:"response_id" json:"response_id"`
	QuestionID pgtype.UUID `db:"question_id" json:"question_id"`
	Value      string      `db:"value" json:"value"`
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRow(ctx, createAnswer, arg.ResponseID, arg.QuestionID, arg.Value)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.ResponseID,
		&i.QuestionID,
		&i.Value,
	)
	return i, err
}

const createForm = `-- name: CreateForm :one

INSERT INTO forms (user_id, title, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, description, created_at, updated_at
`

type CreateFormParams struct {
	UserID      pgtype.UUID `db:"user_id" json:"user_id"`
	Title       string      `db:"title" json:"title"`
	Description string      `db:"description" json:"description"`
}

// +goose StatementBegin
func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, createForm, arg.UserID, arg.Title, arg.Description)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (form_id, type, title, required, position, options, scale_min, scale_max)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, form_id, type, title, required, position, options, scale_min, scale_max, created_at
`

type CreateQuestionParams struct {
	FormID   pgtype.UUID  `db:"form_id" json:"form_id"`
	Type     QuestionType `db:"type" json:"type"`
	Title    string       `db:"title" json:"title"`
	Required bool         `db:"required" json:"required"`
	Position int32        `db:"position" json:"position"`
	Options  []byte       `db:"options" json:"options"`
	ScaleMin pgtype.Int4  `db:"scale_min" json:"scale_min"`
	ScaleMax pgtype.Int4  `db:"scale_max" json:"scale_max"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.FormID,
		arg.Type,
		arg.Title,
		arg.Required,
		arg.Position,
		arg.Options,
		arg.ScaleMin,
		arg.ScaleMax,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Type,
		&i.Title,
		&i.Required,
		&i.Position,
		&i.Options,
		&i.ScaleMin,
		&i.ScaleMax,
		&i.CreatedAt,
	)
	return i, err
}

const createResponse = `-- name: CreateResponse :one
INSERT INTO responses (form_id)
VALUES ($1)
RETURNING id, form_id, submitted_at
`

func (q *Queries) CreateResponse(ctx context.Context, formID pgtype.UUID) (Response, error) {
	row := q.db.QueryRow(ctx, createResponse, formID)
	var i Response
	err := row.Scan(&i.ID, &i.FormID, &i.SubmittedAt)
	return i, err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM forms WHERE id = $1
`

func (q *Queries) DeleteForm(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteForm, id)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getFormByID = `-- name: GetFormByID :one
SELECT id, user_id, title, description, created_at, updated_at FROM forms WHERE id = $1
`

func (q *Queries) GetFormByID(ctx context.Context, id pgtype.UUID) (Form, error) {
	row := q.db.QueryRow(ctx, getFormByID, id)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnswersByResponseID = `-- name: ListAnswersByResponseID :many
SELECT id, response_id, question_id, value FROM answers WHERE response_id = $1
`

func (q *Queries) ListAnswersByResponseID(ctx context.Context, responseID pgtype.UUID) ([]Answer, error) {
	rows, err := q.db.Query(ctx, listAnswersByResponseID, responseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.ResponseID,
			&i.QuestionID,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormsByUserID = `-- name: ListFormsByUserID :many
SELECT id, user_id, title, description, created_at, updated_at FROM forms
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListFormsByUserID(ctx context.Context, userID pgtype.UUID) ([]Form, error) {
	rows, err := q.db.Query(ctx, listFormsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByFormID = `-- name: ListQuestionsByFormID :many
SELECT id, form_id, type, title, required, position, options, scale_min, scale_max, created_at FROM questions
WHERE form_id = $1
ORDER BY position
`

func (q *Queries) ListQuestionsByFormID(ctx context.Context, formID pgtype.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.Type,
			&i.Title,
			&i.Required,
			&i.Position,
			&i.Options,
			&i.ScaleMin,
			&i.ScaleMax,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponsesByFormID = `-- name: ListResponsesByFormID :many
SELECT id, form_id, submitted_at FROM responses
WHERE form_id = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListResponsesByFormID(ctx context.Context, formID pgtype.UUID) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesByFormID, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(&i.ID, &i.FormID, &i.SubmittedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForm = `-- name: UpdateForm :one
UPDATE forms
SET title = $2, description = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, description, created_at, updated_at
`

type UpdateFormParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Title       string      `db:"title" json:"title"`
	Description string      `db:"description" json:"description"`
}

func (q *Queries) UpdateForm(ctx context.Context, arg UpdateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, updateForm, arg.ID, arg.Title, arg.Description)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET type = $2, title = $3, required = $4, position = $5, options = $6, scale_min = $7, scale_max = $8
WHERE id = $1
RETURNING id, form_id, type, title, required, position, options, scale_min, scale_max, created_at
`

type UpdateQuestionParams struct {
	ID       pgtype.UUID  `db:"id" json:"id"`
	Type     QuestionType `db:"type" json:"type"`
	Title    string       `db:"title" json:"title"`
	Required bool         `db:"required" json:"required"`
	Position int32        `db:"position" json:"position"`
	Options  []byte       `db:"options" json:"options"`
	ScaleMin pgtype.Int4  `db:"scale_min" json:"scale_min"`
	ScaleMax pgtype.Int4  `db:"scale_max" json:"scale_max"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Type,
		arg.Title,
		arg.Required,
		arg.Position,
		arg.Options,
		arg.ScaleMin,
		arg.ScaleMax,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.Type,
		&i.Title,
		&i.Required,
		&i.Position,
		&i.Options,
		&i.ScaleMin,
		&i.ScaleMax,
		&i.CreatedAt,
	)
	return i, err
}
