// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type QuestionType string

const (
	QuestionTypeShortText      QuestionType = "short_text"
	QuestionTypeLongText       QuestionType = "long_text"
	QuestionTypeMultipleChoice QuestionType = "multiple_choice"
	QuestionTypeCheckboxes     QuestionType = "checkboxes"
	QuestionTypeDropdown       QuestionType = "dropdown"
	QuestionTypeLinearScale    QuestionType = "linear_scale"
	QuestionTypeDate           QuestionType = "date"
	QuestionTypeTime           QuestionType = "time"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType `json:"question_type"`
	Valid        bool         `json:"valid"` // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

type Answer struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	ResponseID pgtype.UUID `db:"response_id" json:"response_id"`
	QuestionID pgtype.UUID `db:"question_id" json:"question_id"`
	Value      string      `db:"value" json:"value"`
}

type Form struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	UserID      pgtype.UUID        `db:"user_id" json:"user_id"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MagicLink struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Token     string             `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Question struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	FormID    pgtype.UUID        `db:"form_id" json:"form_id"`
	Type      QuestionType       `db:"type" json:"type"`
	Title     string             `db:"title" json:"title"`
	Required  bool               `db:"required" json:"required"`
	Position  int32              `db:"position" json:"position"`
	Options   []byte             `db:"options" json:"options"`
	ScaleMin  pgtype.Int4        `db:"scale_min" json:"scale_min"`
	ScaleMax  pgtype.Int4        `db:"scale_max" json:"scale_max"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Response struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	FormID      pgtype.UUID        `db:"form_id" json:"form_id"`
	SubmittedAt pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
}

type Session struct {
	ID        string             `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	CsrfToken string             `db:"csrf_token" json:"csrf_token"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WebauthnCredential struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	CredentialID []byte             `db:"credential_id" json:"credential_id"`
	PublicKey    []byte             `db:"public_key" json:"public_key"`
	SignCount    int64              `db:"sign_count" json:"sign_count"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WebauthnSession struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Data      []byte             `db:"data" json:"data"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
