// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :one

INSERT INTO webauthn_credentials (user_id, credential_id, public_key, sign_count)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, credential_id, public_key, sign_count, created_at
`

type CreateWebAuthnCredentialParams struct {
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	CredentialID []byte      `db:"credential_id" json:"credential_id"`
	PublicKey    []byte      `db:"public_key" json:"public_key"`
	SignCount    int64       `db:"sign_count" json:"sign_count"`
}

// +goose StatementBegin
func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createWebAuthnCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.CreatedAt,
	)
	return i, err
}

const createWebAuthnSession = `-- name: CreateWebAuthnSession :one
INSERT INTO webauthn_sessions (data, expires_at)
VALUES ($1, $2)
RETURNING id, data, expires_at, created_at
`

type CreateWebAuthnSessionParams struct {
	Data      []byte             `db:"data" json:"data"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateWebAuthnSession(ctx context.Context, arg CreateWebAuthnSessionParams) (WebauthnSession, error) {
	row := q.db.QueryRow(ctx, createWebAuthnSession, arg.Data, arg.ExpiresAt)
	var i WebauthnSession
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredWebAuthnSessions = `-- name: DeleteExpiredWebAuthnSessions :exec
DELETE FROM webauthn_sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredWebAuthnSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredWebAuthnSessions)
	return err
}

const deleteWebAuthnSession = `-- name: DeleteWebAuthnSession :exec
DELETE FROM webauthn_sessions WHERE id = $1
`

func (q *Queries) DeleteWebAuthnSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnSession, id)
	return err
}

const getWebAuthnCredentialByCredentialID = `-- name: GetWebAuthnCredentialByCredentialID :one
SELECT id, user_id, credential_id, public_key, sign_count, created_at FROM webauthn_credentials
WHERE credential_id = $1
`

func (q *Queries) GetWebAuthnCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, getWebAuthnCredentialByCredentialID, credentialID)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.CreatedAt,
	)
	return i, err
}

const getWebAuthnCredentialsByUserID = `-- name: GetWebAuthnCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, sign_count, created_at FROM webauthn_credentials
WHERE user_id = $1
`

func (q *Queries) GetWebAuthnCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, getWebAuthnCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebAuthnSessionByID = `-- name: GetWebAuthnSessionByID :one
SELECT id, data, expires_at, created_at FROM webauthn_sessions
WHERE id = $1
  AND expires_at > NOW()
`

func (q *Queries) GetWebAuthnSessionByID(ctx context.Context, id pgtype.UUID) (WebauthnSession, error) {
	row := q.db.QueryRow(ctx, getWebAuthnSessionByID, id)
	var i WebauthnSession
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateWebAuthnCredentialSignCount = `-- name: UpdateWebAuthnCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = $2
WHERE credential_id = $1
`

type UpdateWebAuthnCredentialSignCountParams struct {
	CredentialID []byte `db:"credential_id" json:"credential_id"`
	SignCount    int64  `db:"sign_count" json:"sign_count"`
}

func (q *Queries) UpdateWebAuthnCredentialSignCount(ctx context.Context, arg UpdateWebAuthnCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnCredentialSignCount, arg.CredentialID, arg.SignCount)
	return err
}
